/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;
import models.Recibo;
import javax.swing.*;
import java.awt.*;
import java.awt.print.PrinterException;

/**
 *
 * @author 46352621
 */
public class DetallesRecibo extends javax.swing.JFrame {
    public static DetallesRecibo instancia = null;
    private Recibo recibo = new Recibo();


    
    
    /**
     * Creates new form DetallesRecibo
     */
    public DetallesRecibo() {
        initComponents();
                
    }
    
    public Recibo getRecibo() {
        return recibo;
    }
    
    
    public void setRecibo(Recibo r) {
        this.recibo = r;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDetalles = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblMomento = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detalles");
        setLocation(new java.awt.Point(100, 100));

        panelDetalles.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Ticket de Recibo");

        lblCliente.setText("Nombre del contribuyente: ");

        lblCodigo.setText("Código de recibo: ");

        lblMomento.setText("Fecha y hora de la operación: ");

        lblMonto.setText("Monto:");

        lblDescripcion.setText("Descripción:");

        javax.swing.GroupLayout panelDetallesLayout = new javax.swing.GroupLayout(panelDetalles);
        panelDetalles.setLayout(panelDetallesLayout);
        panelDetallesLayout.setHorizontalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addGroup(panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblCliente)
                    .addComponent(lblCodigo)
                    .addComponent(lblMomento)
                    .addComponent(lblMonto)
                    .addComponent(lblDescripcion))
                .addGap(0, 531, Short.MAX_VALUE))
        );
        panelDetallesLayout.setVerticalGroup(
            panelDetallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMomento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescripcion)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Imprimir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // Construir el contenido HTML
        String htmlContent = """
            <html>
            <head>
                <style>
                    body { font-family: Arial, sans-serif; margin: 20px; }
                    h1 { text-align: center; }
                    .details { margin-bottom: 20px; }
                    .details div { margin: 5px 0; }
                    .footer { text-align: center; margin-top: 20px; font-style: italic; }
                </style>
            </head>
            <body>
                <h1>Recibo</h1>
                <div class="details">
                    <div><strong>ID:</strong> %s</div>
                    <div><strong>Código:</strong> %s</div>
                    <div><strong>Cliente:</strong> %s</div>
                    <div><strong>Fecha y Hora:</strong> %s</div>
                    <div><strong>Monto:</strong> %s</div>
                    <div><strong>Descripción:</strong> %s</div>
                </div>
                <div class="footer">
                    Gracias por su preferencia.
                </div>
            </body>
            </html>
        """.formatted(
            recibo.getId(),
            recibo.getCodigo(),
            recibo.getCliente(),
            recibo.getMomento(),
            recibo.getMonto(),
            recibo.getDescripcion()
        );
        
        // Crear un componente JEditorPane para renderizar el HTML
        JEditorPane editorPane = new JEditorPane("text/html", htmlContent);
        editorPane.setEditable(false);

        // Configurar el cuadro de diálogo de impresión
        boolean printSuccess;
        try {
            printSuccess = editorPane.print(null, null, true, null, null, true);
            if (printSuccess) {
                JOptionPane.showMessageDialog(null, "El recibo se imprimió correctamente.");
            } else {
                JOptionPane.showMessageDialog(null, "La impresión fue cancelada.");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Error durante la impresión: " + e.getMessage());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetallesRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetallesRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetallesRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetallesRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetallesRecibo().setVisible(true);
            }
        });
    }
    
    
    public void printData() { 
        lblCodigo.setText("Código de recibo: " +recibo.getCodigo());
        lblCliente.setText("Nombre del contribuyente: "+recibo.getCliente());
        lblMomento.setText("Fecha y hora de la operación: "+recibo.getMomento());
        lblMonto.setText("Momento: "+recibo.getMonto());
        lblDescripcion.setText("Descripción: " +recibo.getDescripcion());     
    }
    public static DetallesRecibo getInstancia(Recibo r) {
        if (instancia == null) { 
            instancia = new DetallesRecibo();
            instancia.setRecibo(r);
            instancia.printData();
            instancia.setVisible(true);
            return instancia;
        }
        return instancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblMomento;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JPanel panelDetalles;
    // End of variables declaration//GEN-END:variables
}
